using System;

namespace BubbleBot.Protocol.Enums
{
    public enum ObjectTypeEnum
    {
        Amulette = 1,
        Arc = 2,
        Baguette = 3,
        Bâton = 4,
        Dague = 5,
        Épée = 6,
        Marteau = 7,
        Pelle = 8,
        Anneau = 9,
        Ceinture = 10,
        Bottes = 11,
        Potion = 12,
        Parchemin_d733expérience = 13,
        Item = 14,
        Divers = 15,
        Coiffe = 16,
        Cape = 17,
        Familier = 18,
        Hache = 19,
        Outil = 20,
        Pioche = 21,
        FAUX = 22,
        Dofus = 23,
        Divers_ = 24,
        Document = 25,
        Potion_de_forgemagie = 26,
        Élément_de_mutation = 27,
        Nourriture = 28,
        Bénédiction = 29,
        Malédiction = 30,
        Buff = 31,
        Suit_le_personnage = 32,
        Pain = 33,
        Céréales = 34,
        Fleur = 35,
        Plante = 36,
        Bière = 37,
        Bois = 38,
        Minerai = 39,
        Alliage = 40,
        Poisson = 41,
        Friandise = 42,
        Potion_d733oubli_de_sort = 43,
        Potion_d733oubli_de_métier = 44,
        Potion_d733oubli_de_maîtrise = 45,
        Fruit = 46,
        Os = 47,
        Poudre = 48,
        Poisson_comestible = 49,
        Pierre_précieuse = 50,
        Pierre = 51,
        Farine = 52,
        Plume = 53,
        Poil = 54,
        Tissu = 55,
        Cuir = 56,
        Laine = 57,
        Graine = 58,
        Peau = 59,
        Huile = 60,
        Peluche = 61,
        Poisson_vide = 62,
        Viande = 63,
        Viande_conservée = 64,
        Queue = 65,
        Métaria = 66,
        Légume = 68,
        Viande_comestible = 69,
        Teinture = 70,
        Matériel_d733alchimie = 71,
        Oeuf_de_familier = 72,
        Compétence = 73,
        Fée_d733artifice = 74,
        Parchemin_de_sortilège = 75,
        Parchemin_de_caractéristique = 76,
        Certificat_de_familier = 77,
        Rune_de_forgemagie = 78,
        Boisson = 79,
        Objet_de_quête = 80,
        Sac_à_dos = 81,
        Bouclier = 82,
        Pierre_d733âme = 83,
        Clé = 84,
        Pierre_d733âme_pleine = 85,
        Potion_d733invocation_de_percepteur = 86,
        Parchemin_de_traque = 87,
        Pierre_magique = 88,
        Cadeau = 89,
        Fantôme_de_familier = 90,
        Dragodinde = 91,
        Bouftou = 92,
        Objet_d733élevage = 93,
        Divers__ = 94,
        Planche = 95,
        Écorce = 96,
        Certificat_de_monture = 97,
        Racine = 98,
        Filet_de_capture = 99,
        Sac_de_ressources = 100,
        Arbalète = 102,
        Patte = 103,
        Aile = 104,
        Oeuf = 105,
        Oreille = 106,
        Carapace = 107,
        Bourgeon = 108,
        Oeil = 109,
        Gelée = 110,
        Carapace_ = 111,
        Prisme = 112,
        Objet_vivant = 113,
        Arme_magique = 114,
        Fragment_d733âme_de_Shushu = 115,
        Potion_pour_familier = 116,
        Équipement = 118,
        Champignon = 119,
        Montilier = 121,
        Potion_de_montilier = 122,
        Certificat_de_montilier = 123,
        Fantôme_de_montilier = 124,
        Souvenir = 125,
        Quêtes_principales = 126,
        Quêtes_du_temple = 127,
        Avis_de_recherche = 128,
        Alignement = 129,
        Ordre_de_la_ville = 130,
        Événement = 131,
        Archipel_de_Vulcanie = 132,
        Astrub = 133,
        Quêtes_villes = 134,
        Camp_Bwork = 136,
        Cania = 137,
        Château_d733Amakna = 138,
        L733île_de_Frigost = 139,
        L733île_d733Otomai = 140,
        L733île_de_Nowel = 141,
        Incarnam = 142,
        Montagne_Koalak = 143,
        Pandala = 144,
        Port_de_Madrestam = 145,
        Province_d733Amakna = 146,
        Krosmoz = 147,
        Token = 148,
        Île_de_Moon = 149,
        Îles_Wabbit = 150,
        Trophée = 151,
        Galet = 152,
        Nowel = 153,
        Papier_d733emballage = 154,
        Sufokia = 155,
        Almanax = 156,
        Figurine = 157,
        Rabmablague_Caramel = 158,
        Rabmajoke_Fraise = 159,
        Rabmablague_Citron = 160,
        Rabmablague_Orange = 161,
        Rabmablague_Kola = 162,
        Rabmablague_Nougat = 163,
        Vêtements = 164,
        Potion_de_conquête = 165,
        Mimibiote = 166
    }

    public static class ObjectTypeNameFinder
    {
        public static string GetObjectTypeNameById(int key)
        {
            string result = null;
            result = Enum.GetName(typeof(ObjectTypeEnum), key);
            if (result == null)
                return null;

            result = result.Replace("733", "'");
            result = result.Replace("734", "%");
            result = result.Replace("735", "*");
            result = result.Replace("736", ":");
            result = result.Replace("737", "/");
            result = result.Replace("738", "-");

            while (result.EndsWith("_")) // Remove this for duplicate objects
                result = result.Remove(result.Length - 1);

            result = result.Replace("_", " ");

            return result;
        }
    }
}