<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<CefSharpAnyCpuSupport>true</CefSharpAnyCpuSupport>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.0</TargetFramework>
    <LangVersion>8.0</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Lib\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CefSharp.OffScreen" Version="75.1.143" />
    <PackageReference Include="Google.Apis.Discovery.v1" Version="1.43.0" />
    <PackageReference Include="Google.Apis.Gmail.v1" Version="1.43.0.1835" />
    <PackageReference Include="Newtonsoft.Json" Version="12.0.3" />
    <PackageReference Include="System.Drawing.Common" Version="4.7.0" />
    <PackageReference Include="System.Security.Permissions" Version="4.7.0" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="AntiRecaptcha">
      <HintPath>..\AntiRecaptcha\bin\Debug\AntiRecaptcha.dll</HintPath>
    </Reference>
    <Reference Include="Newtonsoft.Json">
      <HintPath>Lib\Newtonsoft.Json.dll</HintPath>
    </Reference>
    <Reference Include="websocket-sharp">
      <HintPath>Lib\websocket-sharp.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
